# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(507, 551)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        MainWindow.setProperty("toolTipDuration", 2)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 10, 391, 462))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ExpenseButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.ExpenseButton.setObjectName(_fromUtf8("ExpenseButton"))
        self.gridLayout.addWidget(self.ExpenseButton, 7, 0, 1, 1)
        self.CloseButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.CloseButton.setObjectName(_fromUtf8("CloseButton"))
        self.gridLayout.addWidget(self.CloseButton, 9, 0, 1, 1)
        self.IncomeButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.IncomeButton.setObjectName(_fromUtf8("IncomeButton"))
        self.gridLayout.addWidget(self.IncomeButton, 8, 0, 1, 1)
        self.TagDescriptionLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.TagDescriptionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TagDescriptionLabel.setObjectName(_fromUtf8("TagDescriptionLabel"))
        self.gridLayout.addWidget(self.TagDescriptionLabel, 2, 0, 1, 1)
        self.TagEdit = QtGui.QTextEdit(self.gridLayoutWidget)
        self.TagEdit.setObjectName(_fromUtf8("TagEdit"))
        self.gridLayout.addWidget(self.TagEdit, 3, 0, 1, 1)
        self.ValueLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.ValueLabel.setScaledContents(False)
        self.ValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ValueLabel.setObjectName(_fromUtf8("ValueLabel"))
        self.gridLayout.addWidget(self.ValueLabel, 0, 0, 1, 1)
        self.CalendarWidget = QtGui.QCalendarWidget(self.gridLayoutWidget)
        self.CalendarWidget.setObjectName(_fromUtf8("CalendarWidget"))
        self.gridLayout.addWidget(self.CalendarWidget, 5, 0, 1, 1)
        self.ValueEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.ValueEdit.setObjectName(_fromUtf8("ValueEdit"))
        self.gridLayout.addWidget(self.ValueEdit, 1, 0, 1, 1)
        self.CalendarLabel = QtGui.QLabel(self.gridLayoutWidget)
        self.CalendarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.CalendarLabel.setObjectName(_fromUtf8("CalendarLabel"))
        self.gridLayout.addWidget(self.CalendarLabel, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 507, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuAnalysis = QtGui.QMenu(self.menubar)
        self.menuAnalysis.setObjectName(_fromUtf8("menuAnalysis"))
        self.menuStatistics = QtGui.QMenu(self.menuAnalysis)
        self.menuStatistics.setObjectName(_fromUtf8("menuStatistics"))
        self.menuCharts = QtGui.QMenu(self.menuAnalysis)
        self.menuCharts.setObjectName(_fromUtf8("menuCharts"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.ActionAddUser = QtGui.QAction(MainWindow)
        self.ActionAddUser.setObjectName(_fromUtf8("ActionAddUser"))
        self.ActionChangeUser = QtGui.QAction(MainWindow)
        self.ActionChangeUser.setObjectName(_fromUtf8("ActionChangeUser"))
        self.ActionDeleteUser = QtGui.QAction(MainWindow)
        self.ActionDeleteUser.setObjectName(_fromUtf8("ActionDeleteUser"))
        self.ActionShowUsers = QtGui.QAction(MainWindow)
        self.ActionShowUsers.setObjectName(_fromUtf8("ActionShowUsers"))
        self.ActionAverage = QtGui.QAction(MainWindow)
        self.ActionAverage.setCheckable(True)
        self.ActionAverage.setChecked(True)
        self.ActionAverage.setObjectName(_fromUtf8("ActionAverage"))
        self.ActionMedian = QtGui.QAction(MainWindow)
        self.ActionMedian.setCheckable(True)
        self.ActionMedian.setChecked(True)
        self.ActionMedian.setObjectName(_fromUtf8("ActionMedian"))
        self.ActionModa = QtGui.QAction(MainWindow)
        self.ActionModa.setCheckable(True)
        self.ActionModa.setChecked(True)
        self.ActionModa.setObjectName(_fromUtf8("ActionModa"))
        self.ActionStDev = QtGui.QAction(MainWindow)
        self.ActionStDev.setCheckable(True)
        self.ActionStDev.setChecked(True)
        self.ActionStDev.setObjectName(_fromUtf8("ActionStDev"))
        self.ActionVariance = QtGui.QAction(MainWindow)
        self.ActionVariance.setCheckable(True)
        self.ActionVariance.setChecked(True)
        self.ActionVariance.setObjectName(_fromUtf8("ActionVariance"))
        self.ActionLinePlot = QtGui.QAction(MainWindow)
        self.ActionLinePlot.setObjectName(_fromUtf8("ActionLinePlot"))
        self.ActionBarPlot = QtGui.QAction(MainWindow)
        self.ActionBarPlot.setObjectName(_fromUtf8("ActionBarPlot"))
        self.ActionScatterPlot = QtGui.QAction(MainWindow)
        self.ActionScatterPlot.setObjectName(_fromUtf8("ActionScatterPlot"))
        self.ActionShowStats = QtGui.QAction(MainWindow)
        self.ActionShowStats.setObjectName(_fromUtf8("ActionShowStats"))
        self.menuMenu.addAction(self.ActionAddUser)
        self.menuMenu.addAction(self.ActionChangeUser)
        self.menuMenu.addAction(self.ActionDeleteUser)
        self.menuMenu.addAction(self.ActionShowUsers)
        self.menuStatistics.addAction(self.ActionAverage)
        self.menuStatistics.addAction(self.ActionMedian)
        self.menuStatistics.addAction(self.ActionModa)
        self.menuStatistics.addAction(self.ActionStDev)
        self.menuStatistics.addAction(self.ActionVariance)
        self.menuStatistics.addAction(self.ActionShowStats)
        self.menuCharts.addAction(self.ActionLinePlot)
        self.menuCharts.addAction(self.ActionBarPlot)
        self.menuCharts.addAction(self.ActionScatterPlot)
        self.menuAnalysis.addAction(self.menuStatistics.menuAction())
        self.menuAnalysis.addAction(self.menuCharts.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.CloseButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Report Generator", None))
        self.ExpenseButton.setText(_translate("MainWindow", "Add Expense", None))
        self.CloseButton.setText(_translate("MainWindow", "Close", None))
        self.IncomeButton.setText(_translate("MainWindow", "Add Income", None))
        self.TagDescriptionLabel.setText(_translate("MainWindow", "Insert your #tag description", None))
        self.ValueLabel.setText(_translate("MainWindow", "Insert your value", None))
        self.CalendarLabel.setText(_translate("MainWindow", "Choose date of operation", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Users", None))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis", None))
        self.menuStatistics.setTitle(_translate("MainWindow", "Statistics", None))
        self.menuCharts.setTitle(_translate("MainWindow", "Charts", None))
        self.ActionAddUser.setText(_translate("MainWindow", "Add user", None))
        self.ActionChangeUser.setText(_translate("MainWindow", "Change user", None))
        self.ActionDeleteUser.setText(_translate("MainWindow", "Delete user", None))
        self.ActionShowUsers.setText(_translate("MainWindow", "Show users list", None))
        self.ActionAverage.setText(_translate("MainWindow", "Average", None))
        self.ActionMedian.setText(_translate("MainWindow", "Median", None))
        self.ActionModa.setText(_translate("MainWindow", "Moda", None))
        self.ActionStDev.setText(_translate("MainWindow", "Standard Deviation", None))
        self.ActionVariance.setText(_translate("MainWindow", "Variance", None))
        self.ActionLinePlot.setText(_translate("MainWindow", "Line Plot", None))
        self.ActionBarPlot.setText(_translate("MainWindow", "Bar Plot", None))
        self.ActionScatterPlot.setText(_translate("MainWindow", "Scatter Plot", None))
        self.ActionShowStats.setText(_translate("MainWindow", "Show statistics", None))

